### ISSUE TITLE
Weekly Urgencies Email

### ISSUE THREAD

**Issue by APRogers** [tphillips/SERV#32]
Can we schedule weekly emails with that week's requirements in it, send it to the appropriate mailing list as welll as post it to the forum, in an attempt to avoid sending out an SMS every day? We have the email addresses in the system ...

I would suggest every Sunday evening about teatime for the coming week. Separate emails to go to Controllers, Blood Runners, Air Ambulance, Water Run, etc. Some people will get more than one email, at least until the rotas are better populated, but it should cut down on the forum pleas and Spamming everyone with SMS alerts.

**Comment by tphillips** [comment]
This has now been done as a push bullet notification every day at 10am for the next 3 days ahead
